# Generated by Django 4.0.6 on 2022-07-13 13:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('stock_quantity', models.IntegerField()),
                ('price_serving', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderSlip',
            fields=[
                ('order_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=64)),
                ('date_ordered', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=64)),
                ('serving_size', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderslip')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='order.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='ItemAddOn',
            fields=[
                ('item_addon_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('add_on_quantity', models.IntegerField()),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='order.ingredient')),
                ('order_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderitem')),
            ],
        ),
    ]
