# Generated by Django 4.0.6 on 2022-07-13 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220713_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemaddon',
            name='ingredient_id',
            field=models.ForeignKey(db_column='ingredient_id', on_delete=django.db.models.deletion.RESTRICT, to='order.ingredient'),
        ),
        migrations.AlterField(
            model_name='itemaddon',
            name='order_item_id',
            field=models.ForeignKey(db_column='order_item_id', on_delete=django.db.models.deletion.CASCADE, to='order.orderitem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_id',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='order.orderslip'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='recipe_id',
            field=models.ForeignKey(db_column='recipe_id', on_delete=django.db.models.deletion.RESTRICT, to='order.recipe'),
        ),
    ]
